### ISSUE TITLE
Will those files be decrypted when the project is in the release stage?

### ISSUE THREAD

**Issue by ZfsrGhS953** [AJS-development/OpenAgar#12]
As far as I know, OpenAgar is in the development stage right now. I also noticed two files: uid.js (server) and main_out.js (client). They're encrypted currently (with UTF-8 byte codes such as "\x6d"). Will they be decrypted when the project enters its release stage (ready for use by server owners)? Because it isn't going to be OpenAgar otherwise... More like ClosedAgar.

**Comment by Andrews54757** [comment]
No, they are security files to protect servers from bots. Without them being encrypted, they will have no use.

**Comment by Andrews54757** [comment]
We are really strict this time so that bots can be prevented and detected as soon as it connects

**Comment by LegitSoulja** [comment]
@Andrews54757 um, it's not secure andrew!. You encrypted it with no other security as same origin. I did this with the old client if someone steals it and use it for there site, which will redirect back to our site.

As of looking, the client at play.ogarul.io/new does not have that origin protection. Check gitter, i'll provide you the script you MUST add to the bottom of the main out!.

**Comment by LegitSoulja** [comment]
@Andrews54757 Check gitter again -_-

**Comment by Andrews54757** [comment]
@ZfsrGhS953 One more thing. Dont you dare try to ruin OpenAgar too, this project is active, so it is not like OgarUL where we did not do much to disable your bots..

**Comment by LegitSoulja** [comment]
People like him is why OpenAgar is Semi private. People like him is why people can't enjoy things.
People like him doesn't deserve a thing.
People like him knows too much but should use there knowledge on something more productive.
People like him should be discouraged.
People like him should listen to the rules before they deal with the law.
People like him don't understand we can have them fined/sued for disrupting people's property.
People like him is why this world is like it is now.

Using bots I relate as to DDOS. I don't see them harmless, but harmful, and make games unfair. I know agario is boring but we are trying to make it better. We don't need your useless scripts. 

Mainly, all other uknown scripts are trash to us, and we won't allow it, and we take security serious.

If things are encrypted there's a reason why it is. Don't say things as if it will be decrypted. Wasn't that kindof a dumb question?

**Comment by Andrews54757** [comment]
Dont @LegitSoulja . Ranting doesnt help. I was just giving him a little warning

**Comment by LegitSoulja** [comment]
I was giving him that extra salt he was asking for.

**Comment by Merkie** [comment]
Its in hex btw if you want to decode :100:

**Comment by LegitSoulja** [comment]
That's on @Andrews54757 behalf

Shall I encrypt it better with my tools?

**Comment by LegitSoulja** [comment]
It supports es6 btw. I've updated it :)

**Comment by Andrews54757** [comment]
@ZfsrGhS953 Interrupting other peoples streams is not good. Stop it. 

<img width="700" alt="screen shot 2016-12-02 at 10 01 51 pm" src="https://cloud.githubusercontent.com/assets/13282284/20856370/f3f46a40-b8da-11e6-8633-4103138d1e17.png">

**Comment by Andrews54757** [comment]
@LegitSoulja I need to shut down the polarsbots service NOW. It is pushing my buttons too much. Dumb children who are ddosing and whatnot. Dont they know anything about _consequences_? I was given a choice a while ago to be a good programer, or a bad one. I chose the good path. Yet these children are misusing their skills. Ive been intercepting their messages for a long time. I have more than 10 accounts so they cant ban me. and I have seen everything they do and have photographed them. It is really shady and evil, makes me want to personally sue them. I will first contact freenom and discord saying they are violating their terms. I will also contact all the websites they attack and build for them their own bot protection system.

**Comment by Andrews54757** [comment]
I know I shouldnt be obsessed over this. But it is really pushing my buttons

**Comment by Andrews54757** [comment]
First of all. Here are some people who I did background checks and found not so good.


1. @ZfsrGhS953 -> Botter/Ddosser
2. @MastaCoder -> Botting affiliate
3. @P4rtyguy -> Botter/Ddoser


I intend to do a crackdown on these people

**Comment by MastaCoder** [comment]
Yes I am 100% affiliated with them. Yes andrew yes. I own my own Agar.io clone and blocked bots on purpose on it. Yes yes andrew nice guessing.

**Comment by Andrews54757** [comment]
You are slightly innocent. But you are still afiliating with them

**Comment by MastaCoder** [comment]
Just because I'm part of the their discord and I'm a moderator, doesn't mean I'm an affiliate. Look at the chat, look at all the messages I have wrote. I never once said I was botting a website, nor did I say I was working on the code. I am literally just there so I can see their progress on botting my site.

**Comment by MastaCoder** [comment]
Do some research before yelling some dumb crap and tagging me in it.

**Comment by Andrews54757** [comment]
@MastaCoder. I have examined everything.

**Comment by MastaCoder** [comment]
Where are your facts then.

**Comment by MastaCoder** [comment]
Send me where I clearly stated I am working with them, I am working on the code, or I am trying to bot a website. Just show me right now and I'll believe you.

**Comment by MastaCoder** [comment]
I'm waiting.. Come on Mr. Intercept All messages, you should be much faster than this!

**Comment by Andrews54757** [comment]
I am right now sending a 3 page letter to discord. Stop bothering me

**Comment by MastaCoder** [comment]
What happened to me being affiliated then, oh wait. It never happened.

**Comment by MastaCoder** [comment]
> I need to shut down the polarsbots service NOW. It is pushing my buttons too much.
Sick, who cares?

> Dumb children who are ddosing and whatnot.
Clearly you don't understand of how they are showing your flaws. If you can't handle someone showing you what's wrong with your code, it doesn't mean you have to run around crying at them and telling them how much of bad people they are. You're pretty much acting like a kid at this point, someone exploits something in your system. Instead of fixing it or saying, oh right. I can do much better. You sit down, cry about it in a chat, and instead of taking that time to fix it you try to take down the source that is showing you these flaws. We're all behind screens, you taking them down doesn't stop them from going back up.

> Ive been intercepting their messages for a long time.
It's a public discord chat.. Nice intercepting!

> I have more than 10 accounts so they cant ban me.
I actually enjoy seeing you triggered, I don't want you banned!

> and I have seen everything they do and have photographed them
Sounds like a crime scene, oh wait. It's just someone botting someones server. 

> It is really shady and evil, makes me want to personally sue them.
Please don't say sue again if you don't know anything about the law.

> I will first contact freenom and discord saying they are violating their terms.
You have too much time on your hands.

> I will also contact all the websites they attack and build for them their own bot protection system.
It took you 12 sentances to finally say this?

@Andrews54757 Just stop this. You have no idea what you are saying and like to flame war with everyone for just about everything. You try to look professional, but most of the time you run around blurting random nonsense into other peoples faces. Go outside and take a breath. Funny thing is how you're wasting so much time, writing all these paragraphs and "intercepting their messages", while you could get the hell outside or work on the issue. Now stop doing all this dumb crap and fix it already, you're just wasting your own time.

Also, stop saying I'm affiliated. You literally have ***no proof*** whatsoever in no message that I said anything related to them. Yes, I am defending them. Why? Because you are pissing me off. You're that group of programmers that get triggered over the smallest things.

**Comment by Andrews54757** [comment]
@MastaCoder. I am a professional. Do you have any idea of my frustrations when people do the wrong thing? I, who have lived life for a long time, understand that those who start on the wrong path, will stay on the wrong path. 


I am done with you. I will let @LegitSoulja decide your fate.

**Comment by Andrews54757** [comment]
Mabye I should just quit being open source. And force people to pay for once. It seems like the world isnt ready for nice things. You grieve me deeply, and I pray you turn your life around.

**Comment by Andrews54757** [comment]
@LegitSoulja Stop giving out keys until after the year ends.

**Comment by MastaCoder** [comment]
@Andrews54757 Everyone has problems, but they don't react the way you do. (At least normal people) Now you're getting into some bs life stuff that I don't care about. You're clearly ruining your rep in the future. If someone sees posts like this, they'll think about how much you waste time doing useless things. I don't care about what post or anything you did, this is based on your trying to say I'm affiliated in bots in which I am in no way.

Yeah, don't be open source. You're providing too many issues for the people in GitHub. If you're making something closed source, do it somewhere else. GitHub is a place to share and collaborate ideas and code. Not for people like you to cry about how much you hate the world. You seriously need to get some therapy based on that last sentence you just said.

Good, stop giving keys. Make GitHub a bit more cleaner and silenter from kids like you. I would have had no problem with all of this, until you tried to bring up some lies about how I'm affiliated and what not.

**Comment by Andrews54757** [comment]
Locking this for reference.

**Comment by Andrews54757** [comment]
I have decided. I will move out from game creation, to sound engineering and etc. @LegitSoulja You are the new head of AJS. I will start another org. @MastaCoder convinced me enough.

**Comment by LegitSoulja** [comment]
Holdon now what the hell is going on? Let me read.

**Comment by Andrews54757** [comment]
I quit

**Comment by Andrews54757** [comment]
Have a good day everyone!

**Comment by LegitSoulja** [comment]
@Andrews54757 Are you ok? I thought we agreed not to do this? Is it worth it?

**Comment by Andrews54757** [comment]
I am tired with all the complaining. Besides, I hate nodejs. I am going to work with C

**Comment by Andrews54757** [comment]
New org: https://github.com/ThreeLetters

**Comment by Andrews54757** [comment]
gtg

**Comment by LegitSoulja** [comment]
Yes, we no those are little kids, yet there's barely much we can do accept really track them down (which we can), as yes we sue them based upon this https://en.m.wikipedia.org/wiki/Reverse_engineering#Legality

You know I have legal protection, yes I know a few lawyers (friends). I could get them to help in this case, as I've done before at times when I got in trouble with the law.

Lil dude better get a bondsman

**Comment by LegitSoulja** [comment]
I'll look over this sometime soon. I kindof got alerted after the ownership which I knew something bad probably happen and that did come true

**Comment by Andrews54757** [comment]
I dont care in general about legal issues. I am tired of video games. I want to do useful things. I thought people will enjoy it when I develop these kinds of things. But I guess not. And since my motive is helping others, and that is not fulfilled, I quit making games.

**Comment by Andrews54757** [comment]
See you later.

**Comment by Andrews54757** [comment]
Anyway, I have very good ideas. Many you could help. So expect an invitation. :)

**Comment by LegitSoulja** [comment]
@Andrews54757 Well. Um, so what makes you think I really enjoy agar.io in general, or commonly play games? Only every once in the while. I don't even play on my own servers in ogarul. "Only sometimes".

I did at first, but then it got really time wasting and pointless. But I enjoyed working with ogarul.

I only host for entertainment or rather ideas, or rare types of server this is any like no other.

Well, I guess r.i.p ogarul, and r.i.p for me aswell.

@Andrews54757 I hope you're not like very agitated today, and got worked over the bots drama. I told you not to worry unless it get worse. There's always other ways to do things to prevent issues as to that.

Like commonly, you almost damn near built OpenAgar and just quit? You'll never know what the future of OpenAgar will be. Yo either I'm dreaming or trippin or you are right now. Or is this some type of joke?

Sarcasticly, as in slapped myself into reality.

But why? Noo. 

I mean I guess you want, but I'd never seen kids take someone down over this type of nonsense.

If you're going to continue a different path I'll just go back to what I was doing normally "Living life as usual". 

Questions:
Sound engineering? Because I'm into music making and producing 12+ years

Also C, C# or c++, and I thought you said that you was going to learn objective c and make a browser. Why not?

Since you quit making games, what else exactly do you enjoy making? I'm strapped down .net for some dirty work. And not only that but more.

Just let me know about you're future plans, but please don't let these kids get away with it. I told you from the beggining. I've said it a lot of times about how this world is exactly. I sad, kindof wanna just end life. BUT, depression didn't hit me hard enough yet for that too happen lol. I'm good tho,

Well, I'll guess I'll start to plan my 25th bday vacation. I was actually taking this serious but ugh, don't fail on me man.

**Comment by LegitSoulja** [comment]
@Andrews54757 I don't know. If I do something it'll have involve profit. That's since I'm always at home "Not Working. I'm like really tired of school and college 2 years I'm stressed over, and my mom passed a year ago.

**Comment by LegitSoulja** [comment]
Kindof why I'm mostly active. But idk what to do or say extra right now.

**Comment by LegitSoulja** [comment]
Profit meaning, something that'll publically blow. Something that people will actually use.

I have tons of ideas that I've built in the past but never finished. Maybe I should persue

**Comment by Andrews54757** [comment]
@LegitSoulja OpenAgar is not dead yet. I will finish at some point. But it will no longer be priority.

**Comment by LegitSoulja** [comment]
@Andrews54757 don't quit. Without you idk what I'll do.
