### ISSUE TITLE
Invalid key

### ISSUE THREAD

**Issue by AlexandriteErikParacelsus** [AJS-development/OpenAgar#36]
My key was working, when I updated the server it said invalid key. My id is `Hzazdjw8Pdmk1MFxDkIr`
and my old key was `979132941365`

**Comment by Andrews54757** [comment]
We moved all keys to http://opnagar.us. So your key won't work since your key was from the beta testing phase.

**Comment by Andrews54757** [comment]
However, your old key should still work with this: https://github.com/AJS-development/OpenAgar/tree/334d0b1c2129464153337054c4348cfc2369cb83

**Comment by Andrews54757** [comment]
It is because OpenAgar is now very close to being completed, with skins, ddos protection, bugfixes, and more commands added.

**Comment by Andrews54757** [comment]
And we have a key activation/deactivation panel and stuff. People were quick to register on opnagar.us, and you missed it. Sorry. But you will have to wait until next year when we increase the max users count.

**Comment by AlexandriteErikParacelsus** [comment]
;-;

**Comment by LegitSoulja** [comment]
@AlexandriteErikParacelsus Sorry about what happened.

Since you have stuck around for a while, every since OgarUnlimited, I will allow you to have exclusive access to register. I've added your account to the exclusive bypass list.

You should be able to register, and generate your key. 

Thanks for being a good, kind, and patient.

**Comment by LegitSoulja** [comment]
I got a question lol,

what type of party is this? https://github.com/TehHackers/Ogar-unlimmited-party
