### ISSUE TITLE
game isn't ready yet, ? or this is how it will be?!

### ISSUE THREAD

**Issue by systemroot** [AJS-development/OpenAgar#57]
idk if ajs-team like to make it as it is, but as for me are somethings which i don't like. 

1. Blackholes on ffa, (maybe you can create a gamemode which is with blackholes but disable them from ffa)
2. the way how i eat just to touch someone i eat it . that isn't good :confused: 
3. the way how i split, (example when i split too much some of my pices goes back) and isn't possible for tricksplit/popsplit also linesplit doesn't work!
4. just i want to report this, today i got a crazy output on console idk why http://image.prntscr.com/image/8a211f22e9a14d77816ee4504ed255c0.png

maybe you will say pr's are acceptable but i don't know nodejs so don't expect it, just i want to wrote those ideas, now is in your hands to take care for this or to ignore.! :v:

**Comment by FantasyIsBae** [comment]
The popsplits etc , will probably come once everything is sorted .

**Comment by LegitSoulja** [comment]
*sigh*

- Wormholes is on by default. Turn it off if you don't like it. Why is it on? It's a new feature that you'll probably never see if it wasn't.

- The radius of the food when you eat has already been reported.

- 4 is due to some recent changes. Couldn't exactly find where so I'll leave it up to Andrew.

- Pop split, and all that chananagains will fall into place as to what @FantasyIsBae stated.

- And there's no AJS fully. Andrew is the only one who has been working on OpenAgar. 

Well. Didn't know a few #Problems would make someone upset.. 

OpenAgar isn't done yet... There's a few more things needed to be done, as to spectating.

Btw. I'm trying to give Andrew ideas not to make OpenAgar similar to Agar.io, but how the game should've been. So expect that unexpected.

**Comment by LegitSoulja** [comment]
@systemroot

**Comment by LegitSoulja** [comment]
Even a client is needed, the client lags, not the server. 

And there's ALOT of things coming to the future. I will try my best to pay server owners for running servers. You'll get paid by the hour of your server being up. And a lot of client things that I might implement.

My focus:
- Make OpenAgar special. Make it unlike any other private servers. Many gamemodes, functionalities, secrets, and things that'll me the game more interesting. Agar.io is boring atleast.

But anyways, future goals.

**Comment by Andrews54757** [comment]
@systemroot @LegitSoulja The console spamming bug, I could not reproduce. Update again and run npm install

**Comment by systemroot** [comment]
@LegitSoulja get paid per running server that looks nice!

@Andrews54757 thanks

**Comment by LegitSoulja** [comment]
@systemroot bug has been found :)

node_modules/hashbounds/index.js line 96

**Comment by Andrews54757** [comment]
@systemroot Fixed, update your openagar server and run npm install

**Comment by systemroot** [comment]
okay i'll try now
