### ISSUE TITLE
Main_out.js

### ISSUE THREAD

**Issue by Niall7459** [AJS-development/OpenAgar#58]
Hello, I would like to use this with Cigar,

do you have a compatible main_out.js or similar file for Open Agar?

Many thanks!

**Comment by FantasyIsBae** [comment]
Open agar is a semi-private project with files that aren't for public use , this does not work with open agar as it is a completely different

**Comment by LegitSoulja** [comment]
@Niall7459 Since this project is not affiliated with Agar.io, nor Ogar we all can't use the same client. OpenAgar is a unique, rare server with abilities, and extra in-game functionaries that normal Ogar/Agar.io doesn't have. Due to this, Possibilities is even more endless. 

Currently working a on new client that is very very smooth, coded for webgl capabilities. Very smooth, and no lag discovered what so ever. 

Stay tuned.

**Comment by Niall7459** [comment]
Okay that sounds cool.
Is you client for open agar or multiogar

**Comment by LegitSoulja** [comment]
Also, the client is however is private. Noone will be able to lay hands, nor eyes on it. It will be VERY hard to obtain. This is due to security. OpenAgar uses keys and such, and also socket protection. There's just no way possible for other's to use the client, and if I however make this client nobody isn't getting it.

**Comment by LegitSoulja** [comment]
@Niall7459 Client is ONLY for OpenAgar. We are not affiliated with other Ogar software's.

**Comment by Niall7459** [comment]
Aww. So your creating a client for your own use?

**Comment by LegitSoulja** [comment]
Yes.

**Comment by Niall7459** [comment]
Ok.

**Comment by Niall7459** [comment]
I will just stick with my current servers.

**Comment by LegitSoulja** [comment]
Which, when we do, we would not be part of miniclip since they client we are using is basically theirs. So, we are making our owns so we can be our own private thing.

**Comment by Niall7459** [comment]
By the way..
Does OpenAgar have walls. ass in things you cannot pass through?

**Comment by LegitSoulja** [comment]
@Niall7459 Borders? But we can also add new things to OpenAgar if they are suggested by the community. Basically, This is our version of Agar. We can add, or do anything without limitations.

**Comment by Niall7459** [comment]
Okay. still would be great if we could have the client files though. however im sure most would just steel it and you would get no credit.

**Comment by LegitSoulja** [comment]
@Niall7459 It won't be stolen, It can't be.

**Comment by LegitSoulja** [comment]
Even if it was, it wouldn't have functionalities.

**Comment by Niall7459** [comment]
Oh yeah right.

**Comment by LegitSoulja** [comment]
But, Don't test our abilities. The project can't be stolen, the client files as the main_out wouldn't even be seen.

**Comment by Niall7459** [comment]
okay.

**Comment by LegitSoulja** [comment]
You're talking to an experience web dev here. But, I'll give you permissions to TRY and steal the client. All I got to say is good luck doing so.

**Comment by Niall7459** [comment]
I dont want to steal it...
Im guessing you run your own OpenAgar servers then.

**Comment by LegitSoulja** [comment]
Functionalities, meaning the OpenAgar server itself and client validate it's keys, and connections(socket). If the client however was on another domain, you wouldn't work.

And no, we don't run the servers. We make, and host the client. However, the community is which runs the servers.

**Comment by LegitSoulja** [comment]
But it'll be a while maybe 2-3 weeks before OpenAgar officially launch. After the client is finished, and a few more things implemented into OpenAgar.
