### ISSUE TITLE
anderws

### ISSUE THREAD

**Issue by freaky767** [AJS-development/OpenAgar#71]
you a good guy?

**Comment by LegitSoulja** [comment]
@freaky767 why wouldn't he be? He's more than good. Remove the 'o' from good, and that's his name.

**Comment by Andrews54757** [comment]
Well, I am pretty good at programming. Not really god or a master, but pretty good (I started ~2 years ago). Also @LegitSoulja I just saw your message. You did a great job with the client.


> If there is a coding master, ^^^ is (LegitSoulja)

**Comment by LegitSoulja** [comment]
@Andrews54757 

> If there is a coding master, ^^^ is (LegitSoulja)

The sarcasm. I can't take it. xD

**Comment by LegitSoulja** [comment]
Not much in javascript, but I try my best, and only 2 years? I feel as if I should be better in that case, since i've only been programming for 15+ years. Almost 20, not yet though..

**Comment by Andrews54757** [comment]
Woah, thats a lot of years. You have about 15 more years of experience than me. I started programming in 2012-2013 ish. (Started with version of BASIC, then HTML, C, then JS, then C++, (Maybe Python,C# later))

**Comment by Andrews54757** [comment]
I am not the best programmer, or the best person. However, I do learn and improve very fast. I learned JS in a year (Without tutorials, learned by experimentation), then improved it in two. Then learned C++ in a month (With tutorials).


However, I think that is because of the strong willpower I have. I am not physically nor intellectually superior than a lot of people.

**Comment by Andrews54757** [comment]
I do have a weakness though. Everything must be in the "Andrew Bracket". Basically, I mean that I like to set standards, not follow others. Thats why I hate using other people's code. This is a weakness for me though because of the difficulty of certain things, as well as the limits I have.



Its just a weird obsession I have.

**Comment by freaky767** [comment]
i did this as a joke lol, but thanks for the explanation!
