### ISSUE TITLE
Cannot connect, wrong ID, OpenSSL

### ISSUE THREAD

**Issue by Slingou** [AJS-development/OpenAgar#85]
I tried but cant get it working. I thought I can test with no a key?

![capture](https://user-images.githubusercontent.com/25162586/31559427-88a04af2-b01e-11e7-8fda-2cc64a7a62ce.PNG)

Help thanks

**Comment by Andrews54757** [comment]
@Slingou OpenAgar is semi-shutting down

**Comment by Slingou** [comment]
yyy? I guess i will use multi ogar

**Comment by SharkFinPro** [comment]
The site is down, because the person that was hosting it has left AJS @Slingou

**Comment by LegitSoulja** [comment]
@Slingou sorry for the interruption, but I am no longer part of AJS/OpenAgar, and no longer can provide hosting due to my life/career changes.

@Andrews54757 has the content, so it's up to him to bring the site back up. 

I may or may not be back in the future, However I wish good luck to OpenAgar.

@SharkFinPro feel free to take my position in AJS. Good luck to you aswell. 

Take it easy.
