### ISSUE TITLE
Can you publish the workspace of ogarUL?

### ISSUE THREAD

**Issue by Revilum** [AJS-development/OpenAgar#92]
I just want to play ogarUL again but the Website is down and also the github  Repository for the game client also doesn't exist. Maybe you can publish both so people can download it and play it offline (put it on their own website).

**Comment by jerk** [comment]
yes, that would be nice!

**Comment by jerk** [comment]
been a big fan of ogar unlimited for a while, i miss it alot just wish it was available to the public 😄

**Comment by Andrews54757** [comment]
@Revilum @sethdm02 

I guess I can post the client, but it is very complicated to set up - and I wouldn't help. 

1. You cannot just have it on your desktop and run offline. Important components like the UI, skins, and keys must be retrieved over the network
2. You cannot just put any skin library and have it work. I invented a special security system to prevent skin-stealing and this makes putting normal skins impossible.

**Comment by jerk** [comment]
I'd take the time to set it up

**Comment by jerk** [comment]
And no I don't run offline I'd use a server for that

**Comment by Revilum** [comment]
k mee too I have a website

**Comment by jerk** [comment]
**hmmm**

**Comment by Revilum** [comment]
So are you going to do this?

**Comment by Faris90** [comment]
I know an OgarUl client: reroagr.bitballoon.com

**Comment by Revilum** [comment]
ok thank you but i also need the Server Client

**Comment by jerk** [comment]
@Revilum check my repository

**Comment by Revilum** [comment]
ok thank you

**Comment by segg21** [comment]
@Andrews54757 Hey!. I was snooping around and saw this issue. I could possibly get you suitable hosting for **OpenAgar**, and or **OgarUl** and i'll help you bring it back if you would like to continue this work. (_That doesn't mean I stay, but I'll introduce you to the setup_). I think it was kind-of rude of me to just shut down so abruptly, but I honestly just lost interest in this **genre** of gaming, and changed my life a little. I even shut down my sites so there was no direct **hatred** towards the agar community, and was also tempting on deleting my **GitHub**. However, I in fact provided you everything before shutting down.

As of thinking, you could've potentially brought back up everything but I don't think you have any intentions to do so, and I understand. (**_Life_**). But as of the community, they only want **OgarUl**.. **Nodejs** is something we both hate. In the past I attempted to re-write **OgarUl** in another language with no limitation to cores with the required speed to actually run such a server that was fully optimized, but as of the current knowledge now, it's possible to bring back **OgarUl**, but that doesn't make any sense.

> After all the work me and @Andrews54757 have done with **OpenAgar**. Why isn't **OpenAgar** more enough of the satisfaction that **OgarUl** brought? 

If you want **OgarUl** as it was then, there would be no future updates of it and it'll just be the server. As **OgarUl** was built on top of **OgarProject** we don't have full copyright of it to do what we want, nor the client. We didn't own it. There's complications on where the original client came from but it was publicly obtained like **Cigar** has done as the code is almost exactly the same.

**OpenAgar** was then created (client/server), in which everything was copyrighted under us and was wrote the way it should've been and everything was done all for the experience and educational/experimental purposes. 

This was all a non profit organization, (**_Non-Profit_**), and we didn't even add ads to our site for revenue when we received insane amounts of traffic. However there was hope for third party (server owners) to display their own ads but I don't think we would never have, or could've but (fake ads (_join discord_ etc)). But nobody appreciates the work, and that's all we wanted the entire time. But all we got was negative stuff thrown upon us, which impacted our behavior and possibly our work around this organization. 

It was an interesting ride I must say. 

-------------------  

@Revilum @sethdm02 If you want a client, there is one available on this [**org**](https://github.com/AJS-development/client). However, I have no knowledge rather or not it works with the latest release of ogarul if one of you even has it. As of the stage of the latest ogarul client/server, it will be alot of work to make it available for the public. It just wouldn't work if I gave it to you. And idk if we honestly want to go back to the past and use the effort to do so.

If we actually got valid responses from the community publicly, and not just directly me, I think we could've publicly all talked about it and made it the way the community wanted it, however the graphics was one thing we would've eventually majorly pushed out at a later time. You could've experienced some cool WebGL things. But there was no talking and no patience, but we released it early because we kept you patient enough waiting for it, and just kept asking.

I want to see below my comment "hopefully" ALL the things that you want **OpenAgar** to change or fix. We understand you wanted **OgarUl** but what was so special about it? Please share. We honestly don't want to touch **OgarUl**, but bringing **OpenAgar** back is a possibility. But that decision may not be possible in the future.

**Comment by Revilum** [comment]
OgarUL was a reliable private Agar server with easy modding everything was better than the original ogar

**Comment by segg21** [comment]
@Revilum and OpenAgar is more reliable, secured, fast, and modding? Is that all you care about is compatible ogar scripts working with OpenAgar? If so that’s sad unfortunately. Guess no game will ever be played fair without an advantage. 

We’re not bringing OgarUl back just because of modding. Please be more reasonable.

**Comment by Andrews54757** [comment]
@LegitSoulja Woah, whats with the essay above?

**Comment by jerk** [comment]
where did "bringing back" come from. All I Would like this the full client!

**Comment by segg21** [comment]
@sethdm02 “bringing back” was something I suggested. Obviously what you want is already public, besides the working client packets (Which I am guessing is broken). The entire client won’t be released but I’d be more than happy to update the public client. 

But. The original OgarUl client is off limits. Maybe if nobody tried scrapping our sites with bots to steal the client files it would’ve been released, but since everyone has all this knowledge I assume they can get OgarUl and the client working themselves am I correct?

At the end of the day, we made the final decision to obliterate OgarUl. If we wanted to keep it public the repo would still exist. We don’t need you to make it public. We killed it for a reason. Not for someone else to pick up and reclaim for themselves.

**Comment by Andrews54757** [comment]
@LegitSoulja Actually, we killed it because I got overburdened with it. Im fine if someone else has it, as long as it doesnt bother me.

**Comment by segg21** [comment]
@Andrews54757 sure thing. 

A temporary invite into AJS is needed if you want me to update the server/client. 

We will bring the OgarUl repo back and after I am done I will close all pages, and make the repo read only for no more contributions.

Also I don’t know what you’re going to do with OpenAgar but until you want to bring it back and take full responsibility, this repo pages should be closed and made readonly aswell.

**Comment by jerk** [comment]
Alright.

**Comment by jerk** [comment]
Also I don't know if you are talking too me but I'm confused on what you mean by a "temporary invite"

**Comment by segg21** [comment]
@sethdm02 sorry for the confusion, but that was for Andrew.

**Comment by segg21** [comment]
@Revilum @sethdm02 @Faris90

Enjoy https://github.com/AJS-development/OpenAgar/issues/93

**Comment by bonzibuddy801** [comment]
I would play fair

**Comment by Faris90** [comment]
I would play fair

**Comment by Faris90** [comment]
Can I host the OpenAgar client @LegitSoulja ?

**Comment by Cabotrez** [comment]
Yes 😉

**Comment by SharkFinPro** [comment]
No

**Comment by Cabotrez** [comment]
sad

**Comment by Faris90** [comment]
big sad

**Comment by segg21** [comment]
Can’t believe you people are still asking for this.

**Comment by Faris90** [comment]
please @LegitSoulja

**Comment by segg21** [comment]
@Faris90 No! Unless Andrew gives consent of me doing so I will not. I suggest just letting it go because Agar is dead and should forever be!.

**Comment by Faris90** [comment]
https://www.youtube.com/watch?v=2ZIpFytCSVc

**Comment by Faris90** [comment]
https://www.youtube.com/watch?v=BwVZ_tPryDc
